### ISSUE TITLE
Nginx further improvements

### ISSUE THREAD

**Issue by indispeq** [Dsaad-People-Doc/ansible-vagrant#1]
- Change the nginx homepage html file to use a variable that you can set in your playbook.
- Move the contents of your playbook into a 'role' --> lookup ansible roles and recommended directory layouts.
- Only keep the variables in your playbook and the application of the role in there, the rest should go into the new role you will create, you can call it `dsaad-nginx`.

**Comment by Dsaad-People-Doc** [comment]
Implemented
